<?php

namespace AppBundle\Repository;

/**
 * FundTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
