<?php

namespace AppBundle\Repository;

/**
 * LoanTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
