<?php

namespace AppBundle\Repository;

/**
 * FundsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvincesRepository extends \Doctrine\ORM\EntityRepository
{
}
