<?php

namespace AppBundle\Repository;

/**
 * SecuritiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecuritiesRepository extends \Doctrine\ORM\EntityRepository
{
}
